# Generated by Django 5.1.1 on 2024-09-30 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_approvals', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AccreditationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mofaic_clearance', models.FileField(help_text='Upload MOFAIC clearance document', upload_to='clearance/')),
                ('estimated_observers', models.IntegerField(help_text='Enter estimated number of observers')),
                ('observers_list', models.FileField(help_text='Upload list of names of individual observers/monitors', upload_to='observers_list/')),
                ('sponsoring_institution_letter', models.FileField(help_text='Upload introductory letter from sponsoring institution', upload_to='sponsoring_letters/')),
                ('id_document', models.FileField(help_text='Upload copies of national ID or Passport', upload_to='id_documents/')),
                ('passport_photo', models.FileField(help_text='Upload passport size photo (colour, correct dimensions)', upload_to='passport_photos/')),
                ('city_town_district', models.CharField(help_text='Enter city/town/district of stay', max_length=255)),
                ('hotel_facility', models.CharField(help_text='Enter hotel or lodging facility while in Zambia', max_length=255)),
                ('duration_of_stay', models.CharField(help_text='Enter duration of stay in Zambia', max_length=100)),
                ('mission_statement', models.TextField(help_text='Provide summary of mission statement for observer activities')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Application status', max_length=10)),
                ('approval_date', models.DateField(blank=True, help_text='Date the application was approved', null=True)),
                ('approver_name', models.CharField(blank=True, help_text='Name of the person who approved the application', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who created the application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='international_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccreditationApplicationLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_abbreviation', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('physical_address', models.TextField()),
                ('last_name', models.CharField(max_length=255)),
                ('other_names', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('id_number_passport', models.CharField(max_length=50)),
                ('head_of_institution_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('head_phone_number', models.CharField(max_length=20)),
                ('organizational_registration', models.FileField(upload_to='documents/')),
                ('introduction_letter', models.FileField(upload_to='documents/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('approver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accredation_app.accreditationapplication')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
