# Generated by Django 5.1.1 on 2024-10-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accredation_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalObserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_clearance', models.FileField(upload_to='clearances/')),
                ('estimated_number_of_observers', models.IntegerField()),
                ('observers_list', models.FileField(upload_to='observers_list/')),
                ('introductory_letter', models.FileField(upload_to='introductory_letters/')),
                ('identification_docs', models.FileField(upload_to='identifications/')),
                ('passport_photo', models.ImageField(upload_to='passport_photos/')),
                ('city_of_stay', models.CharField(max_length=100)),
                ('lodging_facility', models.CharField(max_length=150)),
                ('duration_of_stay', models.IntegerField()),
                ('country_of_origin', models.CharField(max_length=100)),
                ('city_of_origin', models.CharField(max_length=100)),
                ('mission_statement', models.TextField()),
            ],
        ),
    ]
