# Generated by Django 5.1.1 on 2024-10-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accredation_app', '0002_internationalobserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_abbreviation', models.CharField(max_length=50)),
                ('institution_email', models.EmailField(max_length=254)),
                ('institution_address', models.TextField()),
                ('contact_last_name', models.CharField(max_length=100)),
                ('contact_other_names', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_nrc_number', models.CharField(max_length=20)),
                ('head_full_name', models.CharField(max_length=255)),
                ('head_designation', models.CharField(max_length=100)),
                ('head_phone', models.CharField(max_length=15)),
                ('certificate_of_registration', models.FileField(upload_to='certificates/')),
                ('estimated_number_of_monitors', models.IntegerField()),
                ('monitors_list', models.FileField(upload_to='monitors_list/')),
                ('introductory_letter', models.FileField(upload_to='introductory_letters/')),
                ('identification_docs', models.FileField(upload_to='identifications/')),
                ('passport_photo', models.ImageField(upload_to='passport_photos/')),
                ('physical_address', models.CharField(max_length=255)),
                ('reason_for_application', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='internationalobserver',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='internationalobserver',
            name='contact_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalobserver',
            name='contact_nrc_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='internationalobserver',
            name='contact_other_names',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='internationalobserver',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='internationalobserver',
            name='head_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalobserver',
            name='head_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalobserver',
            name='head_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='internationalobserver',
            name='institution_abbreviation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='internationalobserver',
            name='institution_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalobserver',
            name='institution_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='internationalobserver',
            name='institution_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
