# Generated by Django 5.1.1 on 2024-10-05 22:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accredation_app', '0003_localmonitor_internationalobserver_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalobserver',
            name='approval',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='internationalobserver',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='localmonitor',
            name='approval',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='localmonitor',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
