# Generated by Django 5.1.1 on 2024-10-07 12:48

import accredation_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accredation_app', '0006_internationalobserver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalobserver',
            name='certificate_number',
            field=models.CharField(default=accredation_app.models.InternationalObserver.generate_certificate_no, editable=False, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='localmonitor',
            name='certificate_number',
            field=models.CharField(default=accredation_app.models.LocalMonitor.generate_certificate_no, editable=False, max_length=10, unique=True),
        ),
    ]
